# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_dp')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_dp')
    _dp = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dp', [dirname(__file__)])
        except ImportError:
            import _dp
            return _dp
        try:
            _mod = imp.load_module('_dp', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _dp = swig_import_helper()
    del swig_import_helper
else:
    import _dp
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def new_doublea(nelements):
    return _dp.new_doublea(nelements)
new_doublea = _dp.new_doublea

def delete_doublea(ary):
    return _dp.delete_doublea(ary)
delete_doublea = _dp.delete_doublea

def doublea_getitem(ary, index):
    return _dp.doublea_getitem(ary, index)
doublea_getitem = _dp.doublea_getitem

def doublea_setitem(ary, index, value):
    return _dp.doublea_setitem(ary, index, value)
doublea_setitem = _dp.doublea_setitem

def new_ushorta(nelements):
    return _dp.new_ushorta(nelements)
new_ushorta = _dp.new_ushorta

def delete_ushorta(ary):
    return _dp.delete_ushorta(ary)
delete_ushorta = _dp.delete_ushorta

def ushorta_getitem(ary, index):
    return _dp.ushorta_getitem(ary, index)
ushorta_getitem = _dp.ushorta_getitem

def ushorta_setitem(ary, index, value):
    return _dp.ushorta_setitem(ary, index, value)
ushorta_setitem = _dp.ushorta_setitem

def solve_dp(weights, profits, sets, num_items, num_sets, digits, total_charge, total_charge_diff, solution):
    return _dp.solve_dp(weights, profits, sets, num_items, num_sets, digits, total_charge, total_charge_diff, solution)
solve_dp = _dp.solve_dp
# This file is compatible with both classic and new-style classes.


